version: "3.3"
services:
  frontend:
    # build: ./frontend
    # ports: 
    #   - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
  roulette:
    # build: ./backend/roulette
    # ports:
    #   - "5000:5000"
    volumes:
      - ./backend/roulette:/usr/src/app
